### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tasdv** [woctezuma/steam-market#21] opened 2021-12-23 14:11 UTC
File "C:\Users\User\Desktop\steam-market-master\market_arbitrage_with_foil_cards.py", line 955, in find_item_type_for_app_id
    listing_details = all_listing_details[representative_listing_hash_for_app_id]
KeyError: '400750-15cm SfH 18 (Foil)'

Is that one item causing problems?

**Comment by woctezuma** [comment] 2021-12-23 18:32
The error arises here:
https://github.com/woctezuma/steam-market/blob/413d666e8305692b7163c9828b624c785cf61c84/market_arbitrage_with_foil_cards.py#L950-L955

The `KeyError` indicates that `representative_listing_hash_for_app_id` is not found in the dictionary `all_listing_details`,
where the listing hash is `400750-15cm SfH 18 (Foil)`, which corresponds to this foil card:
https://steamcommunity.com/market/listings/753/400750-15cm%20SfH%2018%20%28Foil%29

I don't know why there is an issue. I need to see if I can reproduce the issue to understand what happens.

**Comment by Tasdv** [comment] 2021-12-24 02:55
You need anything from me to patch it?

**Comment by woctezuma** [comment] 2021-12-24 08:18
For now, I don't need anything from you. I need to find some time to run this function and replicate the bug.

Meanwhile, If you want to avoid this error, you could add a check like this:

https://github.com/woctezuma/steam-market/blob/413d666e8305692b7163c9828b624c785cf61c84/market_arbitrage_with_foil_cards.py#L937-L948

```python   
    if int(app_id) == 400750:
        return None
```

https://github.com/woctezuma/steam-market/blob/413d666e8305692b7163c9828b624c785cf61c84/market_arbitrage_with_foil_cards.py#L950-L958

**Comment by Tasdv** [comment] 2021-12-24 12:34
Yeah just encountered it with some other appIDs

**Comment by woctezuma** [comment] 2021-12-24 13:31
Thank you. I will try the command myself.

I wonder if the issue arises because Steam servers are under stress during the Winter sales. If this is the case, then it is not a bug with the code, but it could be better if the code handled the error and went on until completion.

**Comment by Tasdv** [comment] 2021-12-24 13:33
Is there a way to skip the loading listings from disk and go directly to the second part? Every time I launch the program, it takes 30 mins to complete that, then bugs out at the appIDs part, I'm trying to remove all the bugged ids.

**Comment by woctezuma** [comment] 2021-12-24 13:42
Not sure what you mean, but I guess you could set this to False:
https://github.com/woctezuma/steam-market/blob/413d666e8305692b7163c9828b624c785cf61c84/market_arbitrage_with_foil_cards.py#L1013

**Comment by Tasdv** [comment] 2021-12-24 13:43
No it finishes the first part, where it takes a while, then at the second part, where the bug happens.

**Comment by Tasdv** [comment] 2021-12-24 13:44
> 

yea this worked, it skipped the first part.

**Comment by Tasdv** [comment] 2021-12-24 13:50
The trend I'm seeing so far from the bugged appIDs, are that the marketplace Trading cards have "(Foil)" in them, or some other symbols.

**Comment by woctezuma** [comment] 2021-12-24 13:55
I think `(Foil)` should be normal, because the program only check foil cards.

Other symbols could be an issue. I will see if I can reproduce the issue. If I cannot reproduce the issue, this may be an "encoding" issue, so you would have to ensure that you use `UTF-8` encoding, or something along these lines.

By the way, be aware that you should manually check the goo values with [this bookmarklet](https://gaming.stackexchange.com/a/351941/3921):

![Check goo values](https://i.ibb.co/T18G2rC/2021-12-24-14-51-23.png)

Indeed, I don't know what Valve does, but I suspect they change the amount of gems a trading card is worth from time to time. So it is possible that your local database of goo values has old values for the amount of gems.

**Comment by Tasdv** [comment] 2021-12-24 13:57
I'll try that now

**Comment by Tasdv** [comment] 2021-12-24 14:00
Is there a python script in the program that auto gathers them? Or did you have to do it manually?

**Comment by Tasdv** [comment] 2021-12-24 14:02
I'll execute the program on a vm to see if its just my pc thats bugged.

**Comment by woctezuma** [comment] 2021-12-24 14:04
> Is there a python script in the program that auto gathers them? Or did you have to do it manually?

I think the program will gather them again if you delete this file.

![Goo details](https://i.ibb.co/hZxmBBp/2021-12-24-15-03-13.png)

I have done it once in several runs. Nowadays, the program gathers goo values for new games, and assumes the old goo values are still correct.

**Comment by Tasdv** [comment] 2021-12-24 14:08
Trying now

> > Is there a python script in the program that auto gathers them? Or did you have to do it manually?
> 
> I think the program will gather them again if you delete this file.
> 
> ![Goo details](https://camo.githubusercontent.com/a1c150c22461cd7e7f26e36d18395cdf91606b25434c8ba387483987dc71d4ed/68747470733a2f2f692e6962622e636f2f685a786d4242702f323032312d31322d32342d31352d30332d31332e706e67)
> 
> I have done it once in several runs. I don't remember exactly because it was some time ago. Nowadays, the program gathers goo values for new games, and assumes the old goo values are still correct, if I remember right.

**Comment by Tasdv** [comment] 2021-12-24 14:09
Which python file gathers new good values?

**Comment by woctezuma** [comment] 2021-12-24 14:40
> Which python file gathers new good values?

It is `goo_details_for_foil_cards.json` which gets longer.

**Comment by Tasdv** [comment] 2021-12-24 14:46
I mean which python file do I have to run for it to gather new values?

**Comment by woctezuma** [comment] 2021-12-24 15:07
Closing the issue for now, because I cannot reproduce it. I have run the script just fine till completion.

> I mean which python file do I have to run for it to gather new values?

It should be the same script. If the `.json` file does not exist, the script should look up goo values for every appID.

**Closed by woctezuma** 2021-12-24 15:07 UTC
Labels: bug

**Comment by Tasdv** [comment] 2021-12-25 05:56
If I run the market_arbitrage_with_foil_cards.py, it will just say that the item is not found and move on without creating new ones.
